# scarab/setup/dependencies.py
import subprocess
import shutil
import sys
import secrets
from pathlib import Path

SCARAB_HOME = Path.home() / ".scarab"
ARIA2_CONF  = SCARAB_HOME / "aria2.conf"
ARIA2_DOWNLOADS = SCARAB_HOME / "downloads"

def ensure_aria2() -> bool:
    """
    Makes sure aria2c is available on this system.
    Installs it silently if it isn't.
    Returns True if aria2 is ready to use.
    """
    if shutil.which("aria2c"):
        return True

    print("[scarab] First-time setup...")

    if sys.platform == "darwin":
        return _install_macos()
    elif sys.platform.startswith("linux"):
        return _install_linux()
    elif sys.platform == "win32":
        return _install_windows()

    print("[scarab] ❌ Could not install aria2 automatically on this OS.")
    return False

def _install_macos() -> bool:
    if shutil.which("brew"):
        result = subprocess.run(
            ["brew", "install", "aria2"],
            capture_output=True
        )
        return result.returncode == 0
    return _install_binary_macos()

def _install_linux() -> bool:
    result = subprocess.run(
        ["sudo", "apt-get", "install", "-y", "aria2"],
        capture_output=True
    )
    return result.returncode == 0

def _install_windows() -> bool:
    # Uses winget (available on Windows 10+)
    result = subprocess.run(
        ["winget", "install", "--id", "aria2.aria2", "-e", "--silent"],
        capture_output=True
    )
    return result.returncode == 0

def _install_binary_macos() -> bool:
    """
    Fallback for Macs without Homebrew.
    Downloads the aria2 binary directly into ~/.scarab/bin/
    so it never touches the user's PATH.
    TODO: implement binary download for arm64 and x86_64.
    """
    print("[scarab] ❌ Homebrew not found.")
    print("[scarab]    Install it from https://brew.sh and run scarab again.")
    return False

def setup_aria2_config() -> str:
    """
    Creates aria2 config in ~/.scarab/ on first run.
    Generates a random secret token.
    Returns the token.
    """
    SCARAB_HOME.mkdir(exist_ok=True)
    ARIA2_DOWNLOADS.mkdir(exist_ok=True)

    token_file = SCARAB_HOME / "aria2.token"
    if not token_file.exists():
        token = secrets.token_urlsafe(32)
        token_file.write_text(token)
        token_file.chmod(0o600)  # owner read-only

    token = token_file.read_text().strip()

    ARIA2_CONF.write_text(f"""
# Generated by Scarab — do not edit manually
enable-rpc=true
rpc-listen-all=false
rpc-listen-port=6800
rpc-secret={token}

continue=true
max-concurrent-downloads=3
max-connection-per-server=8
split=8
min-split-size=10M

dir={ARIA2_DOWNLOADS}
log={SCARAB_HOME}/aria2.log
log-level=warn
""".strip())

    return token

def get_aria2_token() -> str:
    token_file = SCARAB_HOME / "aria2.token"
    if not token_file.exists():
        return setup_aria2_config()
    return token_file.read_text().strip()

def start_aria2() -> subprocess.Popen:
    """
    Launches aria2 as a child process of Scarab.
    Returns the process handle for cleanup on exit.
    """
    if not ARIA2_CONF.exists():
        setup_aria2_config()

    return subprocess.Popen(
        ["aria2c", f"--conf-path={ARIA2_CONF}"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )
